### ISSUE TITLE
TypeError: get_updates() missing 1 required positional argument: 'constraints'

### ISSUE THREAD

**Issue by wanfb** [Deep-Learning-Person-Re-Identification/Implementaion-1#33]
Dear author, I came across a problem while compiling your code. I ran " python main.py --dataset cuhk-03.h5, to get the following error. A lot of efforts were paid to solve the problem but I still can't figure it out. Could you please give me some help?

F:\Users\wanfb\Documents\Implementation-CVPR2015-CNN-for-ReID-master\CUHK03>python main.py --dataset cuhk-03.h5
Using TensorFlow backend.
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to
==================================================================================================
input_1 (InputLayer)            (None, 160, 60, 3)   0
__________________________________________________________________________________________________
conv2d_1 (Conv2D)               (None, 156, 56, 20)  1520        input_1[0][0]
                                                                 input_2[0][0]
__________________________________________________________________________________________________
max_pooling2d_1 (MaxPooling2D)  multiple             0           conv2d_1[0][0]
                                                                 conv2d_1[1][0]
                                                                 conv2d_2[0][0]
                                                                 conv2d_2[1][0]
                                                                 conv2d_5[0][0]
                                                                 conv2d_6[0][0]
__________________________________________________________________________________________________
input_2 (InputLayer)            (None, 160, 60, 3)   0
__________________________________________________________________________________________________
conv2d_2 (Conv2D)               (None, 74, 24, 25)   12525       max_pooling2d_1[0][0]
                                                                 max_pooling2d_1[1][0]
__________________________________________________________________________________________________
lambda_1 (Lambda)               (None, 185, 60, 25)  0           max_pooling2d_1[2][0]
                                                                 max_pooling2d_1[3][0]
__________________________________________________________________________________________________
up_sampling2d_1 (UpSampling2D)  (None, 185, 60, 25)  0           max_pooling2d_1[2][0]
                                                                 max_pooling2d_1[3][0]
__________________________________________________________________________________________________
lambda_2 (Lambda)               (None, 185, 60, 25)  0           lambda_1[0][0]
                                                                 lambda_1[1][0]
__________________________________________________________________________________________________
add_1 (Add)                     (None, 185, 60, 25)  0           up_sampling2d_1[0][0]
                                                                 lambda_2[1][0]
__________________________________________________________________________________________________
add_2 (Add)                     (None, 185, 60, 25)  0           up_sampling2d_1[1][0]
                                                                 lambda_2[0][0]
__________________________________________________________________________________________________
conv2d_3 (Conv2D)               (None, 37, 12, 25)   15650       add_1[0][0]
__________________________________________________________________________________________________
conv2d_4 (Conv2D)               (None, 37, 12, 25)   15650       add_2[0][0]
__________________________________________________________________________________________________
conv2d_5 (Conv2D)               (None, 35, 10, 25)   5650        conv2d_3[0][0]
__________________________________________________________________________________________________
conv2d_6 (Conv2D)               (None, 35, 10, 25)   5650        conv2d_4[0][0]
__________________________________________________________________________________________________
concatenate_1 (Concatenate)     (None, 17, 5, 50)    0           max_pooling2d_1[4][0]
                                                                 max_pooling2d_1[5][0]
__________________________________________________________________________________________________
flatten_1 (Flatten)             (None, 4250)         0           concatenate_1[0][0]
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 500)          2125500     flatten_1[0][0]
__________________________________________________________________________________________________
dense_2 (Dense)                 (None, 2)            1002        dense_1[0][0]
==================================================================================================
Total params: 2,183,147
Trainable params: 2,183,147
Non-trainable params: 0
__________________________________________________________________________________________________
Model Compile Successful.
number 0 in 100
start model.fit_generator
Traceback (most recent call last):
  File "main.py", line 108, in <module>
    main(args.dataset_path)
  File "main.py", line 24, in main
    train(model, dataset_path)
  File "main.py", line 49, in train
    model.fit_generator(Data_Generator.flow(f,flag = flag_train),one_epoch,epoch_num,validation_data=Data_Generator.flow(f,train_or_validation=which_v
al_data,flag=flag_val),validation_steps=nb_val_samples, workers=1)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1961, in fit_generator
    self._make_train_function()
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 990, in _make_train_function
    loss=self.total_loss)
TypeError: get_updates() missing 1 required positional argument: 'constraints'

**Comment by RQuispeC** [comment]
Dear all, 
I am having the same problem, I found this https://github.com/the-moliver/kfs/issues/17 and seems to be a problem related with keras version, I have also try some solutions based on it but none works

**Comment by Phoebe-star** [comment]
I use  keras 2.0.0 , it can work,
but use keras 2.0.8 can not work

**Comment by RQuispeC** [comment]
Thanks @Phoebe-star ! it is working now :D

**Comment by qiaoguan** [comment]
i also use keras 2.0.8, there also some wrong,  e.g.    TypeError: get_updates()
so i  change the function in  get_updates in model.py  to this:

def get_updates(self, loss,params):
            grads = self.get_gradients(loss, params)
            self.updates = []
    
            lr = self.lr
            if self.inital_decay > 0:
                lr *= (1. / (1. + self.decay * self.iterations)) ** 0.75
                self.updates .append(K.update_add(self.iterations, 1))
    
            # momentum
            shapes = [K.get_variable_shape(p) for p in params]
            moments = [K.zeros(shape) for shape in shapes]
            self.weights = [self.iterations] + moments
            for p, g, m in zip(params, grads, moments):
                v = self.momentum * m - lr * g  # velocity
                self.updates.append(K.update(m, v))
    
                if self.nesterov:
                    new_p = p + self.momentum * v - lr * g
                else:
                    new_p = p + v
    
                # apply constraints
                if getattr(p, 'constraint', None) is not None:
                    new_p = p.constraint(new_p)
    
                self.updates.append(K.update(p, new_p))
            return self.updates 
and finally it work

**Comment by nbansal90** [comment]
Hello @qiaoguan,

I am using keras 2.1.3 and I am getting similar error

```
2018-02-15 13:13:59.367091: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:05:00.0, compute capability: 6.1)
Using real-time data augmentation.
Traceback (most recent call last):
  File "cifar10_cnn.py", line 106, in <module>
    validation_data=(X_test, Y_test))
  File "/usr/local/keras3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/keras3/lib/python3.5/site-packages/keras/models.py", line 1256, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/keras3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/keras3/lib/python3.5/site-packages/keras/engine/training.py", line 2026, in fit_generator
    self._make_train_function()
  File "/usr/local/keras3/lib/python3.5/site-packages/keras/engine/training.py", line 970, in _make_train_function
    loss=self.total_loss)
TypeError: get_updates() missing 1 required positional argument: 'constraints'
```
Since keras is installed in virtual environment over GPU cluster, I am not sure how should I go about making the changes, which has worked for you. Could you please suggest, how could i move forward.

Nitin

**Comment by Geek-Peng** [comment]
@qiaoguan  I'v used your method ,but ir raised a new Error,
  File "F:/CVPR2015-CNN for P Re-id/Implementation-CVPR2015-CNN-for-ReID-master/CUHK03/main.py", line 48, in train
    nb_val_samples=nb_val_samples)

  File "E:\Anaconda\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "E:\Anaconda\lib\site-packages\keras\engine\training.py", line 2192, in fit_generator
    generator_output = next(output_generator)

  File "E:\Anaconda\lib\site-packages\keras\utils\data_utils.py", line 584, in get
    six.raise_from(StopIteration(e), e)

  File "<string>", line 3, in raise_from

StopIteration.

keras version is 2.1.5
tensorflow-gpu 1.7
python 3.5.2

It seems that , the generator can not iterate.Can you give me some suggests?Thank you so much!

**Comment by TrinhQuocNguyen** [comment]
Hello guys, 

I have tried to rewrite the function:
> get_updates

in file:
> kfs/kfs/optimizers.py 

at this class:
> class NadamAccum(Optimizer)

 and it seems working now. Any feedbacks would be appreciated 😃 😃 😃 

```
    def get_updates(self, loss, params):
        grads = self.get_gradients(loss, params)
        self.updates = [K.update_add(self.iterations, 1)]

        t = (self.iterations + 1.)/self.accum_iters
        accum_switch = K.cast(K.equal((self.iterations + 1.) % self.accum_iters, 0), dtype=K.floatx())

        # Due to the recommendations in [2], i.e. warming momentum schedule
        momentum_cache_t = self.beta_1 * (1. - 0.5 * (K.pow(0.96, t * self.schedule_decay)))
        momentum_cache_t_1 = self.beta_1 * (1. - 0.5 * (K.pow(0.96, (t + 1) * self.schedule_decay)))
        m_schedule_new = self.m_schedule * momentum_cache_t
        m_schedule_next = self.m_schedule * momentum_cache_t * momentum_cache_t_1
        self.updates.append((self.m_schedule, accum_switch*m_schedule_new + (1. - accum_switch)*self.m_schedule))
 
        shapes = [x.shape for x in K.batch_get_value(params)]
        ms = [K.zeros(shape) for shape in shapes]
        vs = [K.zeros(shape) for shape in shapes]
        gs = [K.zeros(shape) for shape in shapes]

        self.weights = [self.iterations] + ms + vs

        for p, gp, m, v, ga in zip(params, grads, ms, vs, gs):

            g = (ga + gp)/self.accum_iters
            # the following equations given in [1]
            g_prime = g / (1. - m_schedule_new)
            m_t = self.beta_1 * m + (1. - self.beta_1) * g
            m_t_prime = m_t / (1. - m_schedule_next)
            v_t = self.beta_2 * v + (1. - self.beta_2) * K.square(g)
            v_t_prime = v_t / (1. - K.pow(self.beta_2, t))
            m_t_bar = (1. - momentum_cache_t) * g_prime + momentum_cache_t_1 * m_t_prime

            self.updates.append(K.update(m, (1. - accum_switch)*m + accum_switch*m_t))
            self.updates.append(K.update(v, (1. - accum_switch)*v + accum_switch*v_t))
            self.updates.append(K.update(ga, (1. - accum_switch)*(ga + gp)))

            p_t = p - self.lr * m_t_bar / (K.sqrt(v_t_prime) + self.epsilon)
            new_p = p_t

            # Apply constraints.
            if getattr(p, 'constraint', None) is not None:
                c = constraints[p]
                new_p = c(new_p)
                
            self.updates.append(K.update(p, (1-accum_switch)*p + accum_switch*new_p))
        return self.updates
```

**Comment by developer88** [comment]
Works for me only with 

```python
print(tf.__version__) # 1.1.0 only
print(keras.__version__) # 2.0.5 only
```
